# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Abhinav Gazta
title: Lead Software Engineer
email: abhinavgazta@gmail.com
# email_title: Email (Email title override)
phone: +91-8130914880
# phone_title: Phone (Phone title override)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: https://www.linkedin.com/in/abhinagazta/


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/abhinav-picture.jpg
about_content: | # this will include new lines to allow paragraphs
  Polyglot developer with 10 years of development experience across several domains.

  Well versed with implementing reactive, asynchronous and eventful architectures, 

  developing business applications in distributed ecosystems for data ingestion, digestion, assimilation and caching.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Lead Software Engineer
        sub_title: Job title
        caption: Date Range (Dec 2017 - present)
        link: Agoda.com
        quote: >
          Booking Holdings ( OTA -: Online Travel Agency )
        description: | # this will include new lines to allow paragraphs
          * Responsible for all systems related to content ingestion, serving of images on agoda. 
          * End to end asynchronous image upload using kafka message queue and cassandra as sink for 180 million  images across 5 DC. Ingestion includes 10 million urls being downloaded, 118 mb/s upload rate, 32 million reads a day.
          * K8 cron scheduled  content ingestion system polling 100+ suppliers content via api/files in pull/push modes. 
          * K8 system digesting 10 million records daily in a producer/consumer setup using kafka, interacting with 150+ sql server tables modelled on domain driven design. System auto refreshes snapshots of data and applies crud ops.  
          * Set up image classification pipeline using retrained resnet-50 image classification cnn model to categorize all images into specific tags.
          * A/B tested on agoda website with big win in experiment and finally integrated. Multiple other image experiments with image types, codecs on carousels like jpeg2000, webp, padding, codecs and integrated. 
          * Built pix back office for adhoc image upload, manipulation, metadata update, soft deletion.
          * Mentoring a lean team of 4 engineers and consistently meeting all okrs. 
    content:
      - layout: left
        title: Senior Software Engineer, MCKINSEY (Consultancy) 4 months
        sub_title: Job title
        link: Mckinsey.com
        quote: >
          Mckinsey( Consultancy )
        description: | # this will include new lines to allow paragraphs
          * Revenue cycle management tool for healthcare providers in US.
          * Worked closely with mckinsey engagement manager, associate partner and partner to understand, 
          translate business requirements into technical solutions. 
          * Assist them with data driven insights for case studies.
    content:
      - layout: left
        title: Senior Software Engineer, GUAVUS (Big Data Analytics Startup/Thales Company) 3.4 yrs
        sub_title: Job title
        link: Guavus.com
        quote: >
          Guavus( Big Data Analytics )
        description: | # this will include new lines to allow paragraphs
          * Actionable analytics on proprietary big data analytics platform and solutions for software defined networks for telecom companies.
          * Created database utilities for purging, backup, restore, aggregation, business cube modelling,
            big data scale persist and retrieval apis, data generators.
          * Worked on integrating open source technologies like spark, sparksql, hbase, oozie, zookeeper onto the platform.
          * Automated testing, validation of the entire platform with over 25k tests
    content:
      - layout: left
        title: Associate Software Engineer, Stryker 1.3 yrs
        sub_title: Job title
        link: Stryker.com
        quote: >
          Stryker( Medical Technology )
        description: | # this will include new lines to allow paragraphs
          * Developed feature auto-freeze for freezing tool tip of navigated device during live surgery inside application
          * N-tier architecture, workflow based application digesting medical dicom images and rendering to 3D models.
          * Design discussions with neurosurgeons for several application enhancements and sales team training on app software.
  - title: Education
    layout: list
    content:
      - layout: left
        title: Punjab Engineering College University Of Technology 
        sub_title: Computer Engineering
        caption: 2007 - 2011
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Google Play Store Mobile Applications Published (hobby) -: 
      * https://play.google.com/store/apps/details?id=com.abhinav.myapp.app&hl=en 
      * https://play.google.com/store/apps/details?id=com.abhinav.rockconcert.rockhead&hl=en 
      * https://play.google.com/store/apps/details?id=com.mygdx.com.abhinav.com.abhinav.game 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
